# -*- coding: utf-8 -*-
"""India Air Quality ETL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KHLu3gSV1_CriU4nV4JM3OQUZBXjnxb3
"""

# importing important libraries and functions of the cleaning script
import pandas as pd
import numpy as np
from cleaning_script import missing_values, check_and_remove_duplicates, save_cleaned_data, handle_outliers

# this function changes the dates from daily to monthly
def daily_to_monthly(df, date_col=None, value_col=None, group_col =None):

  # set dtype to datetime to find wrong date formats
  df[date_col] = pd.to_datetime(df[date_col], errors="coerce")

  # filtering Month and Year out of the date values
  df['Month'] = df[date_col].dt.to_period("M")

  # to generalize the data group by Month, with or without a other column
  df = df.groupby(['Month', group_col])[value_col].mean().reset_index()

  return df

# loading the excel datasets and using my function to seperate the Date, CO and City
df1 = daily_to_monthly(pd.read_excel("AndhraPradesh.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df2 = daily_to_monthly(pd.read_excel("ArunachalPradesh.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df3 = daily_to_monthly(pd.read_excel("Assam.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df4 = daily_to_monthly(pd.read_excel("Bihar.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df5 = daily_to_monthly(pd.read_excel("Chandigarh.xlsx"), date_col='From Date', value_col='CO', group_col='City')

df6 = daily_to_monthly(pd.read_excel("Chattisgarh.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df7 = daily_to_monthly(pd.read_excel("Delhi.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df8 = daily_to_monthly(pd.read_excel("Gujarat.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df9 = daily_to_monthly(pd.read_excel("Haryana.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df10 = daily_to_monthly(pd.read_excel("HimachalPradesh.xlsx"), date_col='From Date', value_col='CO', group_col='City')

df11 = daily_to_monthly(pd.read_excel("JammuKashmir.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df12 = daily_to_monthly(pd.read_excel("Jarkhand.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df13 = daily_to_monthly(pd.read_excel("Karnataka.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df14 = daily_to_monthly(pd.read_excel("Kerala.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df15 = daily_to_monthly(pd.read_excel("MadhyaPradesh.xlsx"), date_col='From Date', value_col='CO', group_col='City')

df16 = daily_to_monthly(pd.read_excel("Maharasthra.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df17 = daily_to_monthly(pd.read_excel("Meghalaya.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df18 = daily_to_monthly(pd.read_excel("Nagaland.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df19 = daily_to_monthly(pd.read_excel("Odisha.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df20 = daily_to_monthly(pd.read_excel("Punducherry.xlsx"), date_col='From Date', value_col='CO', group_col='City')

df21 = daily_to_monthly(pd.read_excel("Punjab.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df22 = daily_to_monthly(pd.read_excel("Rajasthan.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df23 = daily_to_monthly(pd.read_excel("Sikkim.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df24 = daily_to_monthly(pd.read_excel("TamilNadu.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df25 = daily_to_monthly(pd.read_excel("Telangana.xlsx"), date_col='From Date', value_col='CO', group_col='City')

df26 = daily_to_monthly(pd.read_excel("Tripura.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df27 = daily_to_monthly(pd.read_excel("UttarPradesh.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df28 = daily_to_monthly(pd.read_excel("Uttarakhand.xlsx"), date_col='From Date', value_col='CO', group_col='City')
df29 = daily_to_monthly(pd.read_excel("WestBengal.xlsx"), date_col='From Date', value_col='CO', group_col='City')

# adding every dataset to a list to easier join them together
df_list = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13,
           df14, df15, df16, df17, df18, df19, df20, df21, df22, df23, df24,
           df25, df26, df27, df28, df29]

# join every dataset in the list together
df_merged = pd.concat(df_list, ignore_index=True)

# giving the first merged dataset an understandable name
df_from_2021 = df_merged

# cleaning several things with the cleaning script
df_from_2021 = handle_outliers(df_from_2021)
df_from_2021 = missing_values(df_from_2021)
df_from_2021 = check_and_remove_duplicates(df_from_2021)

# loading the csv datasets
df_city = pd.read_csv("city_day.csv")
df_station_day = pd.read_csv("station_day.csv")
df_station = pd.read_csv("stations.csv")

# merging "station day" and "station" to get a connection to "city"
df_station_day = df_station_day.merge(df_station[['City', 'StationId']], on='StationId', how='left')

# changing the date using my function
df_station_day = daily_to_monthly(df_station_day, 'Date', 'CO', 'City')
df_city = daily_to_monthly(df_city, 'Date', 'CO', 'City')

# merging "city" and "station day" to have all values together
df_from_2015_to_2020 = pd.concat([df_city, df_station_day])

# cleaning this data with my cleaning script
df_from_2015_to_2020 = handle_outliers(df_from_2015_to_2020)
df_from_2015_to_2020 = missing_values(df_from_2015_to_2020)
df_from_2015_to_2020 = check_and_remove_duplicates(df_from_2015_to_2020)

# putting all together to one dataset with every value
df_from_2015_to_2023 = pd.concat([df_from_2015_to_2020, df_from_2021])

# watching the dataset reminds me to clean unrealistic zero values
cols_with_invalid_zeros = ["CO"]
# values marking as NaNs
df_from_2015_to_2023[cols_with_invalid_zeros] = df_from_2015_to_2023[cols_with_invalid_zeros].replace(0.0, np.nan)

# filling NaNs with the mean
for col in cols_with_invalid_zeros:
  df_from_2015_to_2023[col] = df_from_2015_to_2023[col].fillna(df_from_2015_to_2023[col].mean())

# saving the complete dataset
df_from_2015_to_2023.to_excel("India CO in Air from 2015 to 2023.xlsx", index=False)